version: '3.1'

services:
  gpt-db:
    image: postgres
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB}
    volumes:
      - ./database/db:/var/lib/postgresql/data
    ports:
      - '${DATABASE_PORT}:5432'
