export enum LogService {
	NEW_GAME_FORM_ACTION = 'new_game_form_action',

	GAME_SERVICE = 'GAME_SERVICE',
	GAME_REPOSITORY = 'GAME_REPOSITORY',

	EXPLORE_PAGE = 'EXPLORE_PAGE',

	AREA_REPOSITORY = 'AREA_REPOSITORY',
	AREA_SERVICE = 'AREA_SERVICE',
	AREA_SERVICE_HELPER = 'AREA_SERVICE_HELPER',

	COLLECTIBLE_TYPE_SERVICE = 'COLLECTIBLE_TYPE_SERVICE',
	COLLECTIBLE_TYPE_REPOSITORY = 'COLLECTIBLE_TYPE_REPOSITORY',

	COLLECTIBLE_SERVICE = 'COLLECTIBLE_SERVICE',
	COLLECTIBLE_REPOSITORY = 'COLLECTIBLE_REPOSITORY',
	COLLECTIBLE_SERVICE_HELPER = 'COLLECTIBLE_SERVICE_HELPER',

	FILE_HANDLER = 'FILE_HANDLER',

	CACHED_COLLECTIBLE_TYPE_STORE = 'CACHED_COLLECTIBLE_TYPE_STORE',
	CACHED_AREA_STORE = 'CACHED_AREA_STORE',

	ACHIEVEMENT_SERVICE = 'ACHIEVEMENT_SERVICE',
	ACHIEVEMENT_REPOSITORY = 'ACHIEVEMENT_REPOSITORY',

	FRANCHISE_SERVICE = 'FRANCHISE_SERVICE',
	FRANCHISE_REPOSITORY = 'FRANCHISE_REPOSITORY',

	PUBLISHER_SERVICE = 'PUBLISHER_SERVICE',
	PUBLISHER_REPOSITORY = 'PUBLISHER_REPOSITORY',

	DEVELOPER_SERVICE = 'DEVELOPER_SERVICE',
	DEVELOPER_REPOSITORY = 'DEVELOPER_REPOSITORY',

	GENRE_SERVICE = 'GENRE_SERVICE',
	GENRE_REPOSITORY = 'GENRE_REPOSITORY',

	PLATFORM_SERVICE = 'PLATFORM_SERVICE',
	PLATFORM_REPOSITORY = 'PLATFORM_REPOSITORY',

	STOREFRONT_SERVICE = 'STOREFRONT_SERVICE',
	STOREFRONT_REPOSITORY = 'STOREFRONT_REPOSITORY',

	API_PARENT_TITLE_GET = 'API_PARENT_TITLE_GET',
	API_GAME_COVER_IMAGE_IMAGE_NAME_GET = 'API_GAME_COVER_IMAGE_IMAGE_NAME_GET',

	QUERY_TO_SERVICE_PAGINATION_ADAPTER = 'QUERY_TO_SERVICE_PAGINATION_ADAPTER'
}
